FROM python:3.11-slim
WORKDIR /app
COPY pyproject.toml /app/pyproject.toml
RUN pip install --no-cache-dir -U pip && pip install --no-cache-dir -e .
COPY apps /app/apps
EXPOSE 8501
CMD ["streamlit", "run", "apps/frontend/streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]
